### ISSUE TITLE
DTS-CD is not supported

### ISSUE THREAD

**Issue by merbanan** [foo86/dcadec#23]
http://wiki.multimedia.cx/index.php?title=DCA#14-bit_words describes it briefly.

http://www.diatonis.com/surround_sound_music.html has some samples.

avconv/ffmpeg -codec dca -i file.wav -acodec copy out.dts

will get the raw dts bitstream.

**Comment by Aleksoid1978** [comment]
as write in documentation:

Parse DTS packet. Packet data must be already converted into 16-bit
big-endian format. Caller must have already established byte stream
synchronization. Packet must start with a valid 32-bit sync word. EXSS frame
must be aligned on 4-byte boundary if present in the packet.

DTSinWAV - store in 14-bit BE/LE format. that's why you think that don't support.

**Comment by foo86** [comment]
> as write in documentation:

He probably means that ‘dcadec’ application doesn't parse such files. That's true, only 16-bit big- and little-endian words are supported by rudimentary DTS bytestream parser that's built in. Patches for implementing 14-bit support are welcome.
