### ISSUE TITLE
Change the behavior of the downmix flags

### ISSUE THREAD

**Issue by jamrial** [foo86/dcadec#35]
As the subject says, the current behavior of the downmix flags is inconsistent.
Having the 2ch flag output a downmix only if there are custom downmix coefficients and forcing a 5.1 downmix otherwise, the 6ch outputting a 5.1 dowmix regardless of custom coefficients being available or not, and the two flags together being the only way to force a stereo downmix seems an odd decision.
I propose the following to be implemented before the first version is tagged and released, which will allow library users more freedom when requesting a downmix:

DCADEC_FLAG_KEEP_DMIX_2CH and DCADEC_FLAG_KEEP_DMIX_6CH flags when used alone should output the relevant downmix only if there are custom coefficients available, otherwise they should output the stream untouched.
The 2ch and 6ch flags used together should first try a stereo downmix if custom coefficients are available, if not then a 5.1 downmix if custom coefficients are available. If neither is possible then it should output the stream untouched.
A new "force" flag used in conjunction with any one of the above flags should force the output of the relevant downmix, regardless of custom coefficients being present or not.
The two downmix flags used together in conjunction with the force flag should behave the same way as 2ch + force.
The force flag used alone should be ignored.

The reason for this is that library users would rather deal with the downmix themselves in cases where there are no custom coefficients of any kind embedded in the stream, and the current state of the flags simply doesn't allow this.
Suggestions to improve the above are of course welcome, but this definitely needs to be addressed before the first version is released.

**Comment by foo86** [comment]
Current behavior of the downmix flags may seem odd at first, but it is based around practical consideration of how 6.1 and 7.1 content is encoded in DTS streams. There is always a backward compatible 5.1 core present, which represents a 6.1 → 5.1 or 7.1 → 5.1 downmix. Any extra channels are encoded as separate channel sets in extension sub-streams. 

2.0 downmix is different. It can be directly embedded as a separate channel set (an unusual, but possible configuration for Master Audio), there can be 5.1 → 2.0 downmixing coefficients present in the stream so that decoder can perform the downmix using these, or downmixing coefficients can be absent.

Consider the following cases when decoding a hypothetical 7.1 stream:
- Neither KEEP_DMIX_2CH nor KEEP_DMIX_6CH flags are set. Decoder processes extra channel sets and performs 5.1 → 7.1 downmix reversal.
- KEEP_DMIX_6CH flag is set. 5.1 core is decoded and extra channel sets are skipped.
- KEEP_DMIX_2CH flag is set. If there is a 2.0 downmix embedded as a separate channel set, it is decoded and output as is. If there are 5.1 → 2.0 downmixing coefficients present, 5.1 core is decoded and 5.1 → 2.0 downmix is performed. In there are no downmixing coefficients present, 5.1 core is decoded and output as is (since the user wants 2.0 output anyway, it seems wasteful for libdcadec to perform 5.1 → 7.1 downmix reversal and then require the caller to perform 7.1 → 2.0 downmix).
- Both KEEP_DMIX_2CH and KEEP_DMIX_6CH flags are set. The same as KEEP_DMIX_2CH flag alone, except that 2.0 downmix is forced using default 5.1 → 2.0 downmixing coefficients.

I hope this explains why the current behavior of downmixing flags was chosen. I think it already gives enough freedom for library users to deal with downmixing. Perhaps KEEP_DMIX_2CH flag behavior in absence of downmixing coefficients can be changed to produce full 7.1 output, so that the caller can perform 7.1 → 2.0 downmix (instead of 5.1 → 2.0 downmix) using whatever coefficients it likes, but I don't think it is a big deal.
