### ISSUE TITLE
Bitstream navigation error

### ISSUE THREAD

**Issue by madshi** [foo86/dcadec#36]
dcadec reports "Bitstream navigation error" with this file:

http://madshi.net/problem.dtshd

**Comment by foo86** [comment]
Looks like a broken file to me. Decoding a frequency band data segment in one XLL frame results in overread of 2 bits, that's not supposed to happen under normal circumstances.

This can be worked around by ignoring overread completely (reference decoder doesn't seem to care anyway), though that will most likely result in corrupt output. Unless this problem recurs with different files, I don't think adding such workaround is feasible.

Commit 81121d1 changes XLL decoder behavior so that an error in one segment doesn't cause entire frame parsing to fail, thus keeping amount of non-losslessly decoded data at minimum (only 1/8 of XLL frame is lost instead of 2 full frames as it did previously).

**Comment by madshi** [comment]
Thanks for looking into it.

Currently, if I enable strict mode, decoding of this file fails. When disabling strict mode, is succeeds - without any apparent warnings. Is there a way to get warnings but still let decoding succeed? That's not really a crucial feature, IMHO, but eac3to users have been asking about that. If you don't consider it important/useful, that's just fine with me.

**Comment by foo86** [comment]
Printing a warning to users needs some kind of logging framework, which the library doesn't currently have. It might be added in the future.

**Comment by madshi** [comment]
Ok, thanks.

**Comment by MarcusJohnson91** [comment]
I'm not at all an expert in programming, but in my bit reading library, I simply use fprintf to stderr, is that not possible here?

**Comment by Nevcairiel** [comment]
Ideally a library doesn't print to stdout or stderr, but offers a way for an application that uses the library to determine what to do with logging. So libdcadec should not print to stderr, while dcadec.c can, since its a CLI application.

**Comment by MarcusJohnson91** [comment]
I see. So maybe the decoding functions could pass it up the chain to dcadec?

**Comment by ghost** [comment]
In this case, the simplest solution would be setting some flag that the API user can query.

**Comment by foo86** [comment]
> Currently, if I enable strict mode, decoding of this file fails. When disabling strict mode, is succeeds - without any apparent warnings. Is there a way to get warnings but still let decoding succeed?

As @wm4 suggested, `dcadec_context_filter()` will now return positive value when Master Audio frame is suspected to be decoded non-losslessly (due to failed segment in non-strict decoding mode or sync error, or when clipping is detected). Decoding application can for example count such frames and print a warning if there are too many.

**Comment by madshi** [comment]
Thanks!

So I suppose a positive value means a "warning" and a negative value means an "error", and 0 means everything's perfect, right?

Two wishes:

1) If strict mode is disabled, can you create a "warning" in all those situations where strict mode would return an "error"?

2) Can you support "dcadec_strerror()" for warnings, too?

If implemented this way, I suppose we don't really need a strict mode, anymore, because the only difference would be that strict mode would raise warnings up to error level, right?

**Comment by foo86** [comment]
> So I suppose a positive value means a "warning" and a negative value means an "error", and 0 means everything's perfect, right?

Correct.

> 1) If strict mode is disabled, can you create a "warning" in all those situations where strict mode would return an "error"?
> 2) Can you support "dcadec_strerror()" for warnings, too?

That's an interesting suggestion... I think it can be done. `dcadec_context_parse()` can be similarly extended to return positive warning codes.

> If implemented this way, I suppose we don't really need a strict mode, anymore, because the only difference would be that strict mode would raise warnings up to error level, right?

Basically, yes.

**Comment by madshi** [comment]
Cool, I'd like it.

**Comment by foo86** [comment]
I've committed a change that adds concept of warnings so that strict mode flag can be dropped for normal decoding. Now both `dcadec_context_parse()` and `dcadec_context_filter()` return positive warning code in all cases where error would be returned in strict mode.

**Comment by madshi** [comment]
And "dcadec_strerror()" now works for warnings, too?

**Comment by foo86** [comment]
Yes.

**Comment by madshi** [comment]
Wonderful - thanks!  :-)
